import type { Metadata } from "next";
import { Cabin_Sketch as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Learn-Shadcn.iu",
  description: "Generated by Next.js by JcxMéndezz ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="{fontSans.variable}">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.className,
          fontSans.variable
        )}
      >
        {children}
      </body>
      ;
    </html>
  );
}
